### ISSUE TITLE
allow the window to be moved

### ISSUE THREAD

**Issue by Sasmira** [DC23/jd-easytimekeeping#108]
Would it be possible to make the window move and paste like the one in Small Time?

**Comment by DC23** [comment]
Possible, yes.
Do I have any idea how to do this yet? No!
Am I willing to learn? Yes!
Will I do this before the first release to Foundry? No, but only because I don't know how long it will take. Since I'm learning Foundry dev as I go, everything is unknown. This could be simple; it could be tricky. So, for the first release I am focused on the core features needed for the module to work. I'll definitely implement this in the next batch of improvements.
