### ISSUE TITLE
Localization string in settings

### ISSUE THREAD

**Issue by pafvel** [DC23/jd-easytimekeeping#133]
The default names in Daily Shift Settings show up as localization strings, such as JDTIMEKEEPING.Shift.Morning

Version tested: v 0.6.6

**Comment by DC23** [comment]
I saw this last night too, but it was 11pm and thought it was just because I'd installed an earlier version of the world in the module. It's because the shortcut localization approach only works in some places. Easy fix, thanks for reporting.

**Comment by DC23** [comment]
Reopening, as moving module settings registration to the ready hook is having an unintended consequence:
`Uncaught (in promise) Error: "jd-easytimekeeping.uiTextColor" is not a registered game setting`

The issue is that the first render of the `UIPanel` class requires looking up module settings, and now those settings aren't available in time, leading to the exception. The module still works, since the UI gets another render call due to an initial time update which succeeds before the user gets to see anything, but this error annoys me. There are another couple of options to explore.

It's still valid to have customisable strings with localizable default values, I just need to work out the best way to handle initialization of those that works correctly with all the timing interdependencies of the Foundry initialization process. Failing that, I have a workaround that's less elegant - initialize to an empty string, wrap these strings in accessors that check for 'false-ish' values and return the localized default in that case. I then need to ensure that all uses of these strings use the accessor instead of loading the string directly. 

First step: see if the `i18n` hook occurs at a workable time for my other dependencies. If so, problem solved.
