### ISSUE TITLE
Customizable days names

### ISSUE THREAD

**Issue by vegon** [DC23/jd-easytimekeeping#169]
Title. It would help with immersion. 

And also, if possible, change the numbers of days per week (useful for people using the Faerun calendar).

**Comment by DC23** [comment]
![weekday-names](https://github.com/user-attachments/assets/4c96fa6b-f043-4a8f-abbb-45de4033c838)
I've implemented this (will be in release v0.9.0) for 7 weekdays.

At present, the names only appear in the hover text on the graphical clock for days of the week. I'm going to make a new issue for redoing the first display line in the screenshot that reads "9:45 AM on day 26". What I really want is simple:
- a short time display as default. It just shows the time in 12 or 24 hour time. I already have that.
- a more standard long-form time display, showing time, day and week.

I'm going to do this right away but need to track it as a new feature because it's a discrete chunk of work.
